### PR TITLE
Use AWS SSM to manage PostgreSQL password

### PR DESCRIPTION
**Pull request by LucianU**
First draft.

### CODE REVIEW

**Comment by RaduCStefanescu** [comment]
Hi @LucianU 
Thank you for the PR!
Based on the activity on the repository, our idea is to have the whole configuration loaded from an environment variable called `CONFIG`
That means that we will load the whole json containing the configuration in the AWS SSM variable.

**Comment by LucianU** [comment]
@RaduCStefanescu, what would the config consist of? And how do you parse the JSON?

**Comment by RaduCStefanescu** [comment]
@LucianU the config has the structure detailed in this file 
https://github.com/code4romania/theater-hub-api/blob/master/src/config/env/_common.ts

The JSON is already parsed by the framework I believe, and the magic happens in this file:
https://github.com/code4romania/theater-hub-api/blob/master/src/config/env/index.ts

So, instead of having an environment variable for each of the database URL, the database password, etc, we have just one variable where we keep the entire CONFIG. The framework will take care of the parsing of the file.

**Comment by LucianU** [comment]
@RaduCStefanescu, using a JSON file for config instead of Terraform variables raises a question: how do we extract certain information from that JSON, so we can use it in Terraform?

For example, we want the PostgreSQL password so we can set it when we create the user. If we set that in the JSON file, we need to parse that file with Terraform. I can't find anywhere that this is possible. Can we do this?

**Comment by LucianU** [comment]
This could be closed, since it's outdated.

**Pull request closed without merging**
